server:
  port: 8080

spring:
  application:
    name: spring-boot-prometheus

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}